name: edus_tutor
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  file_picker: ^5.5.0
  file_utils: ^1.0.1
  flutter_bloc: ^8.1.3
  lottie: ^2.6.0
  flutter_calendar_carousel: ^2.4.2
  flutter_cupertino_date_picker_fork: ^1.0.7
#  flutter_cupertino_localizations: ^1.0.1
  flutter_local_notifications: ^15.1.1
  flutter_webview_plugin: 
    git: https://github.com/jiankian/flutter_webview_plugin
  http: ^1.1.0
  open_filex: ^4.3.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  fancy_shimmer_image: ^2.0.3
  url_launcher: ^6.1.14
  logger: ^2.0.2
  auto_size_text: ^3.0.0
  flutter_svg: 
#  age: ^0.0.1
  age:
    path: ./age
  intl: ^0.18.1
  timeago: ^3.5.0
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.5.0
  pdf_flutter:
    git: https://github.com/erluxman/pdf_flutter
  cached_network_image: ^3.3.1
  flutter_inappwebview: ^5.7.2+3
  extended_image: ^8.1.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  edge_alerts: ^0.0.1
  flutter_screenutil: ^5.9.0
  flutter_widget_from_html: ^0.10.5+3
  permission_handler: ^11.0.0
  http_auth: ^1.0.3
  flutter_paystack: ^1.0.7
#  flutter_paystack:
#    git:
#      url: https://github.com/definitelyme/flutter_paystack.git
#      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_credit_card: ^3.0.7
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar: ^5.0.2
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  get: ^4.6.6
  google_fonts: ^5.1.0
  badges: ^3.1.2
  themify_flutter:
    path: ./themify_flutter
  stripe_sdk: ^5.0.0
  flutter_portal: ^1.1.4
  file: ^7.0.0
  loading_more_list: ^5.0.3
  flutter_easyloading: ^3.0.5
  photo_view: ^0.14.0
  better_player: ^0.0.83

  razorpay_flutter: ^1.3.5
  reorderables:
    git: https://github.com/emran92/reorderables
  pusher_channels_flutter: ^2.2.0
  khalti: ^1.1.0
  html_editor_enhanced: ^2.5.1
  universal_html: ^2.2.4
  #eko_jitsi: ^1.3.8
#  eko_jitsi:
#    git: https://github.com/emran92/eko_jitsi

#  html_editor_enhanced:
#    git: https://github.com/ksilz/html-editor-enhanced
  flutter_html: ^2.2.1
  change_app_package_name: ^1.1.0
  image_picker: ^1.0.4
  dots_indicator: ^3.0.0
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  import_sorter: ^4.6.0

dependency_overrides:
  intl: ^0.17.0
  file_picker: ^5.2.7
  shimmer: ^2.0.0
  flutter_slidable: ^0.6.0-nullsafety.0
  http: ^0.13.6
#  firebase_core: ^1.17.0
#  firebase_messaging: ^11.4.0
  flutter_widget_from_html: ^0.8.5
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  file: ^6.1.4
  flutter_html: ^3.0.0-alpha.5
  stripe_sdk: ^5.0.0-nullsafety.1


# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/app_icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/config/app_logo1.png
  fullscreen: true
  color: "FFFFFF"


flutter:
  uses-material-design: true
  assets:
   - assets/config/
   - assets/images/
   - assets/locale/

fonts:
  - family: popins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 100
      - asset: fonts/poppins_bold.ttf
        weight: 200
      - asset: fonts/poppins_light.ttf
        weight: 300
      - asset: fonts/poppins_regular.ttf
        weight: 400
      - asset: fonts/poppins_semibold.ttf
        weight: 500
