/// GENERATED FILE, DO NOT EDIT!

import 'package:flutter/widgets.dart';

class Themify {
  Themify._();

  static const _kFontFam = 'Themify';
  static const _kFontPackage = 'themify_flutter';

  static const IconData agenda =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData alarm_clock = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData alert = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData align_center = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData align_justify = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData align_left = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData align_right =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData anchor =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData android =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_double_down =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_double_left =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_double_right =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_double_up =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_down =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_left =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_right =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData angle_up =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData announcement =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData apple =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData archive =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_circle_down =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_circle_left =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_circle_right =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_circle_up =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_down =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_left =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_right =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_top_left =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_top_right =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow_up =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrow =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrows_corner =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrows_horizontal =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData arrows_vertical =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData back_left =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData back_right =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bag =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bar_chart_alt =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bar_chart =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData basketball =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bell =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData blackboard =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bolt_alt =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bolt =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData book =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bookmark_alt =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bookmark =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData briefcase =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData brush_alt =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData brush =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData calendar =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData camera =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData car =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData check_box =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData check =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData clip =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData clipboard =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData close =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cloud_down =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cloud_up =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cloud =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData comment_alt =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData comment =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData comments_smiley =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData comments =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_backward =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_eject =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_forward =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_pause =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_play =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_record =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_shuffle =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_skip_backward =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_skip_forward =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData control_stop =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData credit_card =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData crown =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData css3 =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cup =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cut =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData dashboard =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData desktop =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData direction_alt =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData direction =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData download =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData dribbble =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData dropbox_alt =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData dropbox =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData drupal =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData email =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData envelope =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData eraser =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData exchange_vertical =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData export_icon =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData eye =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData face_sad =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData face_smile =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData facebook =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData file =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData files =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData filter =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData flag_alt_2 =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData flag_alt =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData flag =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData flickr_alt =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData flickr =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData folder =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData fullscreen =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData gallery =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData game =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData gift =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData github =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData google =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hand_drag =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hand_open =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hand_point_down =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hand_point_left =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hand_point_right =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hand_point_up =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hand_stop =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData harddrive =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData harddrives =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData headphone_alt =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData headphone =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData heart_broken =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData heart =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData help_alt =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData help =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData home =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData html5 =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hummer =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData id_badge =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData image =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData import_icon =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData infinite =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData info_alt =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData info =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData ink_pen =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData instagram =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData italic =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData joomla =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData jsfiddle =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData key =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layers_alt =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layers =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_accordion_list =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_accordion_merged =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_accordion_separated =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_column2_alt =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_column2 =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_column3_alt =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_column3 =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_column4_alt =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_column4 =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_cta_btn_left =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_cta_btn_right =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_cta_center =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_cta_left =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_cta_right =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_grid2_alt =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_grid2_thumb =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_grid2 =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_grid3_alt =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_grid3 =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_grid4_alt =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_grid4 =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_line_solid =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_list_large_image =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_list_post =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_list_thumb_alt =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_list_thumb =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_center_alt =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_center =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_left_alt =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_left =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_overlay_alt_2 =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_overlay_alt =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_overlay =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_right_alt =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_media_right =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_menu_full =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_menu_separated =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_menu_v =
      IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_menu =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_placeholder =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_sidebar_2 =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_sidebar_left =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_sidebar_none =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_sidebar_right =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_slider_alt =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_slider =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_tab_min =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_tab_v =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_tab_window =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_tab =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_width_default_alt =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_width_default =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout_width_full =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData light_bulb =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData line_dashed =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData line_dotted =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData line_double =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData link =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData linkedin =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData linux =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData list_ol =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData list =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData location_arrow =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData location_pin =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData lock =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData loop =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData magnet =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData map_alt =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData map =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData marker_alt =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData marker =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData medall_alt =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData medall =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData menu_alt =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData menu =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData microphone_alt =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData microphone =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData microsoft_alt =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData microsoft =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData minus =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData mobile =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData money =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData more_alt =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData more =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData mouse_alt =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData mouse =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData music_alt =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData music =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData na =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData new_window =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData notepad =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData package =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData paint_bucket =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData paint_roller =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData palette =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData panel =
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData paragraph =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pencil_alt =
      IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pencil_alt2 =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pencil =
      IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pie_chart =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pin_alt =
      IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pin =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pin2 =
      IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pinterest_alt =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pinterest =
      IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData plug =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData plus =
      IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData power_off =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData printer =
      IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pulse =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData quote_left =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData quote_right =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData receipt =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData reddit =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData reload =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData rocket =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData rss_alt =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData rss =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData ruler_alt_2 =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData ruler_alt =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData ruler_pencil =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData ruler =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData save_alt =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData save =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData search =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData server =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData settings =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData share_alt =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData share =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData sharethis_alt =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData sharethis =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shield =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shift_left_alt =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shift_left =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shift_right_alt =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shift_right =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shine =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shopping_cart_full =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shopping_cart =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shortcode =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData signal =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData skype =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData slice =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData smallcap =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData soundcloud =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData split_h =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData split_v_alt =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData split_v =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData spray =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData stack_overflow =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData stamp =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData star =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData stats_down =
      IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData stats_up =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData support =
      IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData tablet =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData tag =
      IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData target =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData text =
      IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData themify_favicon_alt =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData themify_favicon =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData themify_logo =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData thought =
      IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData thumb_down =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData thumb_up =
      IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData ticket =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData time =
      IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData timer =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData trash =
      IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData trello =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData truck =
      IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData tumblr_alt =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData tumblr =
      IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData twitter_alt =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData twitter =
      IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData underline =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData unlink =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData unlock =
      IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData upload =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData uppercase =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData user =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData vector =
      IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData video_camera =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData video_clapper =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData view_grid =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData view_list_alt =
      IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData view_list =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData vimeo_alt =
      IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData vimeo =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData volume =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData wallet =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData wand =
      IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData wheelchair =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData widget_alt =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData widget =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData widgetized =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData window =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData wordpress =
      IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData world =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData write =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData yahoo =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData youtube =
      IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData zip =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData zoom_in =
      IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData zoom_out =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
}
